#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
BorcTakip Release Signing Kurulumu - Otomatik
İnteraktif setup - Kullanıcı girdisini alır
"""

import os
import subprocess
import base64
import sys
import getpass
from pathlib import Path
import shutil

# Renk kodları
GREEN = '\033[92m'
RED = '\033[91m'
YELLOW = '\033[93m'
CYAN = '\033[96m'
END = '\033[0m'

def print_title(text):
    print("\n" + "="*80)
    print(f" {text}")
    print("="*80 + "\n")

def print_success(text):
    print(f"{GREEN}✅ {text}{END}")

def print_error(text):
    print(f"{RED}❌ {text}{END}")

def print_info(text):
    print(f"{YELLOW}ℹ️  {text}{END}")

def print_step(num, text):
    print(f"{CYAN}[{num}/5] {text}{END}\n")

def get_input(prompt, default=""):
    val = input(f"{prompt} [{default}]: ").strip()
    return val if val else default

def get_password(prompt):
    while True:
        pwd = getpass.getpass(f"{prompt}: ")
        if pwd:
            return pwd
        print_error("Şifre boş olamaz!")

# ============= ANA KURULUM =============

print_title("BorcTakip Release Signing Kurulumu")

keystore_path = "release-key.keystore"
sdk_dir = f"C:\\Users\\{os.getenv('USERNAME')}\\AppData\\Local\\Android\\Sdk"

# ADIM 1: Keystore Kontrol
print_step(1, "Keystore Dosyası Kontrol Ediliyor")

if os.path.exists(keystore_path):
    size = os.path.getsize(keystore_path) / 1024
    print_success(f"release-key.keystore bulundu ({size:.1f} KB)")
else:
    print_error("release-key.keystore bulunamadı!")
    print("\nLütfen release-key.keystore dosyasını proje root'una kopyalayın.")
    print("Veya yeni keystore oluşturmak için .github/KULLANICILAR_KEYSTORE_KURULUMU.md oku")
    sys.exit(1)

# ADIM 2: Şifreler
print_step(2, "Keystore Bilgileri Girin")

key_alias = get_input("Key Alias", "release-key")
keystore_pass = get_password("Keystore Şifresi")
key_pass = get_password("Key Şifresi (aynı olabilir)")

# ADIM 3: local.properties Oluştur
print_step(3, "local.properties Oluşturuluyor")

local_props = f"""## This file is automatically generated by Android Studio.
# Do not modify this file -- YOUR CHANGES WILL BE ERASED!
#
# This file should *NOT* be checked into Version Control Systems,
# as it contains information specific to your local configuration.
#
sdk.dir={sdk_dir}

# Gemini API Key
GEMINI_API_KEY=AIzaSyAUzi7qz-V1dwomDaVWMO9gNGF4fQng4oM

# Release Signing Configuration
BORC_TAKIP_STORE_FILE=release-key.keystore
BORC_TAKIP_STORE_PASSWORD={keystore_pass}
BORC_TAKIP_KEY_ALIAS={key_alias}
BORC_TAKIP_KEY_PASSWORD={key_pass}
"""

try:
    with open("local.properties", "w", encoding="utf-8") as f:
        f.write(local_props)
    print_success("local.properties oluşturuldu")
except Exception as e:
    print_error(f"local.properties oluşturulamadı: {e}")
    sys.exit(1)

# ADIM 4: Build Test
print_step(4, "Build Test Çalıştırılıyor")
print(f"{YELLOW}Komut: gradlew :app:assembleDebug{END}\n")

result = subprocess.run(
    "gradlew.bat :app:assembleDebug",
    shell=True,
    capture_output=True,
    text=True
)

if result.returncode == 0:
    print_success("Build başarılı!")
else:
    print_error("Build başarısız!")
    print(result.stderr)
    sys.exit(1)

# ADIM 5: Base64 SIGNING_KEY
print_step(5, "Base64 SIGNING_KEY Oluşturuluyor")

try:
    with open(keystore_path, "rb") as f:
        keystore_bytes = f.read()
    
    base64_string = base64.b64encode(keystore_bytes).decode("utf-8")
    
    # Clipboard'a kopyala
    process = subprocess.Popen("clip", stdin=subprocess.PIPE, shell=True)
    process.communicate(base64_string.encode("utf-8"))
    
    print_success("Base64 SIGNING_KEY oluşturuldu!")
    print_success("Clipboard'a kopyalandı!")
    print(f"\nBase64 (ilk 50 karakter): {base64_string[:50]}...")
    print(f"Toplam uzunluk: {len(base64_string)} karakter\n")
    
except Exception as e:
    print_error(f"Base64 oluşturulamadı: {e}")

# FINAL: GitHub Talimatları
print_title("KURULUM TAMAMLANDI!")

print_success("✅ release-key.keystore kullanılıyor")
print_success("✅ local.properties güncellenmiştir")
print_success("✅ Build test başarılı")
print_success("✅ Base64 SIGNING_KEY oluşturuldu")

print(f"\n{CYAN}GitHub'da Eklenecek Secrets:{END}\n")

print(f"{YELLOW}1. BORC_TAKIP_STORE_PASSWORD{END}")
print(f"{YELLOW}2. BORC_TAKIP_KEY_ALIAS = {key_alias}{END}")
print(f"{YELLOW}3. BORC_TAKIP_KEY_PASSWORD{END}")
print(f"{YELLOW}4. SIGNING_KEY (Clipboard'da - kopyalandı){END}\n")

print(f"{CYAN}SONRA YAPACAK:{END}")
print("  1. https://github.com/burhan2855/borctakip/settings/secrets/actions")
print("     👉 Yukarıdaki 4 Secret'i ekleyin\n")

print("  2. Test commit:")
print("     git push origin develop\n")

print("  3. GitHub Actions'ı izleyin:")
print("     https://github.com/burhan2855/borctakip/actions\n")

print(f"{GREEN}🎉 Kurulum tamamlandı! GitHub'da Secrets ekledikten sonra ready!{END}\n")
