@echo off
REM Setup Keystore ve GitHub Secrets
REM Bu script kullanıcıların kendi şifrelerini girmesini sağlar

setlocal enabledelayedexpansion

cls
echo.
echo ================================================================================
echo  BorcTakip Release Signing Kurulumu
echo ================================================================================
echo.
echo Bu script sihayla keystore kurulumunu yapacaksınız.
echo Kendi şifrelerinizi güvenli şekilde gireceksiniz.
echo.
echo ================================================================================

REM Keystore dosyası kontrol
echo.
echo [1/5] Keystore Dosyası Kontrol Ediliyor...
if exist release-key.keystore (
    echo ✅ release-key.keystore bulundu
) else (
    echo ❌ release-key.keystore bulunamadı!
    echo.
    echo Seçenekler:
    echo A) Yeni keystore oluştur (bu script oluşturacak)
    echo B) Mevcut keystore'u kopyala
    echo.
    set /p KEYSTORE_CHOICE="Seçiminiz (A/B): "
    
    if /i "!KEYSTORE_CHOICE!"=="A" (
        echo.
        echo Yeni keystore oluşturuluyor...
        echo.
        echo Keystore bilgilerini giriniz (hepsi opsiyonel, Enter'a basarak geçebilirsiniz):
        echo.
        set /p KEY_CN="Adınız (Common Name) [Burhan]: "
        if "!KEY_CN!"=="" set "KEY_CN=Burhan"
        
        set /p KEY_OU="Organizasyon Birimi [BorcTakip]: "
        if "!KEY_OU!"=="" set "KEY_OU=BorcTakip"
        
        set /p KEY_O="Organizasyon Adı [BorcTakip]: "
        if "!KEY_O!"=="" set "KEY_O=BorcTakip"
        
        set /p KEY_L="Şehir [Turkey]: "
        if "!KEY_L!"=="" set "KEY_L=Turkey"
        
        set /p KEY_ST="Bölge [Turkey]: "
        if "!KEY_ST!"=="" set "KEY_ST=Turkey"
        
        set /p KEY_C="Ülke Kodu [TR]: "
        if "!KEY_C!"=="" set "KEY_C=TR"
        
        echo.
        set /p KEYSTORE_PASS="Keystore Şifresi (min 6 karakter): "
        if "!KEYSTORE_PASS!"=="" (
            echo ❌ Şifre boş olamaz!
            exit /b 1
        )
        
        set /p KEY_ALIAS="Key Alias [release-key]: "
        if "!KEY_ALIAS!"=="" set "KEY_ALIAS=release-key"
        
        set /p KEY_PASS="Key Şifresi (Keystore şifre ile aynı olabilir): "
        if "!KEY_PASS!"=="" set "KEY_PASS=!KEYSTORE_PASS!"
        
        REM Keystore oluştur
        echo.
        echo Keystore oluşturuluyor (RSA 2048, 10000 gün geçerli)...
        keytool -genkeypair ^
            -alias !KEY_ALIAS! ^
            -keyalg RSA ^
            -keysize 2048 ^
            -keystore release-key.keystore ^
            -validity 10000 ^
            -keypass !KEY_PASS! ^
            -storepass !KEYSTORE_PASS! ^
            -dname "CN=!KEY_CN!, OU=!KEY_OU!, O=!KEY_O!, L=!KEY_L!, ST=!KEY_ST!, C=!KEY_C!"
        
        if errorlevel 1 (
            echo ❌ Keystore oluşturma başarısız!
            exit /b 1
        )
        echo ✅ Keystore başarıyla oluşturuldu!
    ) else if /i "!KEYSTORE_CHOICE!"=="B" (
        echo.
        echo Mevcut keystore dosyasını proje root'una kopyalayın.
        echo Dosya adı: release-key.keystore
        echo.
        pause
        echo.
    ) else (
        echo ❌ Geçersiz seçim!
        exit /b 1
    )
)

REM local.properties oluştur/güncelle
echo.
echo [2/5] local.properties Dosyası Oluşturuluyor...

if exist local.properties (
    echo ℹ️ local.properties zaten var. Keystore bilgileri eklenecek.
) else (
    echo ℹ️ local.properties oluşturuluyor...
)

REM Şifreleri sor
echo.
echo Keystore bilgilerini giriniz:
echo.

if not defined KEY_ALIAS (
    set /p KEY_ALIAS="Key Alias [release-key]: "
    if "!KEY_ALIAS!"=="" set "KEY_ALIAS=release-key"
)

if not defined KEYSTORE_PASS (
    set /p KEYSTORE_PASS="Keystore Şifresi: "
    if "!KEYSTORE_PASS!"=="" (
        echo ❌ Şifre boş olamaz!
        exit /b 1
    )
)

if not defined KEY_PASS (
    set /p KEY_PASS="Key Şifresi: "
    if "!KEY_PASS!"=="" set "KEY_PASS=!KEYSTORE_PASS!"
)

REM local.properties dosyasını oluştur
(
    echo ## This file is automatically generated by Android Studio.
    echo # Do not modify this file -- YOUR CHANGES WILL BE ERASED!
    echo #
    echo # This file should *NOT* be checked into Version Control Systems,
    echo # as it contains information specific to your local configuration.
    echo #
    echo sdk.dir=C:\\Users\\%USERNAME%\\AppData\\Local\\Android\\Sdk
    echo.
    echo # Gemini API Key
    echo GEMINI_API_KEY=AIzaSyAUzi7qz-V1dwomDaVWMO9gNGF4fQng4oM
    echo.
    echo # Release Signing Configuration
    echo BORC_TAKIP_STORE_FILE=release-key.keystore
    echo BORC_TAKIP_STORE_PASSWORD=!KEYSTORE_PASS!
    echo BORC_TAKIP_KEY_ALIAS=!KEY_ALIAS!
    echo BORC_TAKIP_KEY_PASSWORD=!KEY_PASS!
) > local.properties

echo ✅ local.properties güncellenmiştir.

REM Lokal test build
echo.
echo [3/5] Lokal Build Test Ediliyor...
echo.
echo Komut: gradlew :app:assembleDebug
call gradlew.bat :app:assembleDebug

if errorlevel 1 (
    echo ❌ Build başarısız oldu!
    echo Hataları kontrol edin ve tekrar deneyin.
    pause
    exit /b 1
)
echo ✅ Build başarılı!

REM GitHub Secrets talimatları
echo.
echo [4/5] GitHub Secrets Talimatları
echo.
echo GitHub'da şu 4 Secret'i eklemeli siniz:
echo.
echo 1. BORC_TAKIP_STORE_PASSWORD = !KEYSTORE_PASS!
echo 2. BORC_TAKIP_KEY_ALIAS = !KEY_ALIAS!
echo 3. BORC_TAKIP_KEY_PASSWORD = !KEY_PASS!
echo 4. SIGNING_KEY = (Base64 Keystore - aşağıda oluşturacağız)
echo.

echo Base64 SIGNING_KEY oluşturuluyor...
REM PowerShell kullanarak Base64'e kodla
for /f "delims=" %%A in ('powershell -Command "[System.Convert]::ToBase64String([System.IO.File]::ReadAllBytes((Get-Location).Path + '\release-key.keystore'))" 2^>nul') do set "BASE64_KEY=%%A"

if not defined BASE64_KEY (
    echo ⚠️ Base64 otomatik oluşturulamadı.
    echo Lütfen şunu çalıştırın:
    echo.
    echo PowerShell:
    echo $base64 = [Convert]::ToBase64String([IO.File]::ReadAllBytes("release-key.keystore"))
    echo $base64 ^| Set-Clipboard
    echo.
) else (
    echo ✅ Base64 SIGNING_KEY oluşturuldu.
    echo Clipboard'a kopyalanacak...
    REM Windows'ta clipboard'a kopyalama
    echo %BASE64_KEY% | clip
    echo ✅ Clipboard'a kopyalandı!
)

REM GitHub Instructions
echo.
echo [5/5] GitHub Setup
echo.
echo Lütfen aşağıdaki adımları takip edin:
echo.
echo 1. GitHub Repository'nize gidin:
echo    https://github.com/burhan2855/borctakip/settings/secrets/actions
echo.
echo 2. "New repository secret" butonuna tıklayın
echo.
echo 3. Dört Secret'i aşağıdaki gibi ekleyin:
echo.
echo    Secret 1:
echo    Name: BORC_TAKIP_STORE_PASSWORD
echo    Value: !KEYSTORE_PASS!
echo.
echo    Secret 2:
echo    Name: BORC_TAKIP_KEY_ALIAS
echo    Value: !KEY_ALIAS!
echo.
echo    Secret 3:
echo    Name: BORC_TAKIP_KEY_PASSWORD
echo    Value: !KEY_PASS!
echo.
echo    Secret 4:
echo    Name: SIGNING_KEY
if defined BASE64_KEY (
    echo    Value: (Clipboard'dan yapıştır - otomatik kopyalandı)
) else (
    echo    Value: (Manual olarak Base64 keystore'unuzu giriniz)
)
echo.
echo 4. Tüm Secret'leri ekledikten sonra, ilk test commit'i yapın:
echo    git push origin develop
echo.
echo 5. GitHub Actions sekmesinde çalışmaları izleyin:
echo    https://github.com/burhan2855/borctakip/actions
echo.

echo.
echo ================================================================================
echo  ✅ KURULUM TAMAMLANDI!
echo ================================================================================
echo.
echo ✅ Keystore oluşturuldu: release-key.keystore
echo ✅ local.properties güncellenmiştir
echo ✅ Build test başarılı
echo ✅ GitHub Secrets talimatları gösterildi
echo.
echo SONRA YAPACAK:
echo  1. GitHub'da 4 Secret ekleyin
echo  2. git push origin develop (test)
echo  3. GitHub Actions'ta çalışmaları izleyin
echo.
echo ================================================================================
echo.

pause
